### ISSUE TITLE
RunScript(service.rpm,suspend)?

### ISSUE THREAD

**Issue by klodeckl** [b-jesch/service.rpm#1]
Hello,
I would like to suspend after the rpm script was running. Is something like RunScript(service.rpm,suspend) also possible? I think it is currently not implemented in service.py.

**Comment by b-jesch** [comment]
If you choose "Shutdown performed by Kodi" the rpm uses the shutdown method selected in Settings -> System -> Power Saving.  This also happens on a script call like RunScript(service.rpm,poweroff). "poweroff" at this point is only a command/keyword to initiate the stop procedure.

**Comment by klodeckl** [comment]
Good to know, thank you for the information.

So the best would be to change the theme that there would be only one shutdown option (the theme offers shutdown, suspend and hibernate)? My intention was to run rpm for every of this options and then execute a shutdown, suspend or hibernate.

Currently I have set shutdown method by OS. Could you tell me the difference and advantage/disadvantage of this instead of using shutdown using Kodi?

**Comment by b-jesch** [comment]
Shutdown by OS (Linux only) excecutes a shellscript: https://github.com/b-jesch/service.rpm/blob/master/resources/lib/shutdown.sh . This method is sometimes more stable then the Kodi builtin methods.

Shutdown via Kodi use the mechanism of the builtin shutdown routines. Kodi is able to detect the possible methods of your system, so this is more accurate at this point.

**Comment by klodeckl** [comment]
Thanks for your explanation, it works as described (although it would be better to have the option how to shutddown). However when using suspend and the system wakes up again, the countdown of the addon to shutdown (suspend) the system runs again, it must be cancelled. And (in my case) the addon takes a long time to start the shutdown. Maybe I will better switch to a raspberry pi ;)
