### ISSUE TITLE
Computer powers off before comskip ends (pidoff "-x" switch is not working in libreelec 11.0.3 Generic.x86_64)

### ISSUE THREAD

**Issue by EDavidzar** [b-jesch/service.rpm#4]
Helllo, I'm, David:

When i recorded with tvheadend some films and i'm using comskip to mark commercials, the computer (mini pc) powers off before comskip ends.
I'm using kernel Linux LibreELEC 6.1.38  SMP Sat Jul 15 09:30:06 UTC 2023 x86_64 GNU/Linux version 11.0.3.
libreElec pidof is in BusyBox v1.32.1 (2023-07-15 08:51:54 UTC) multi-call binary and the "-x" switch doesn't exist:

pidof: invalid option -- 'x'
BusyBox v1.32.1 (2023-07-15 08:51:54 UTC) multi-call binary.

Usage: pidof [OPTIONS] [NAME]...

List PIDs of all processes with names that match NAMEs

	-s	Show only one PID
	-o PID	Omit given pid
		Use %PPID to omit pid of pidof's parent
I don't know if this is a issue or not.
Greetings
David

**Comment by scriptorron** [comment]
@b-jesch : Maybe it is more portable to use Pythons `psutil` instead of a system command. A usage example is here: https://www.tutorialspoint.com/how-to-get-the-list-of-running-processes-using-python
But I am not sure if `psutil` is installed by default on all systems.

Alternatively you can parse the outputs of `ps ax` which seems to be available on all Linux-like OS.

**Comment by EDavidzar** [comment]
Hello again, testing pidoff in LibreElec with only "pidof" without -x works for commands and scripts, psutils is not installed in LibreElec and it can not be  installed.

**Comment by b-jesch** [comment]
On Ubuntu `pidof -x` works as expected. As I'm remember correctly, this option was introduced for dectection of running shell scripts. While busybox seems to have another implementation of pidof it's required to distuingish between special implementations like Libre-/CoreElec and others Linux implementations (Ubuntu, Debian, ...) and therefore deciding to should use pidof with/without the -x option. Should be doable.

**Comment by EDavidzar** [comment]
thank you very much.
